apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodejstest
        image: prajwaldockerhub/nodejs-test:latest
        ports:
        - containerPort: 3000
        resources:
         requests: 
          cpu: 200m
          memory: 128Mi
         limits:
          cpu: 500m
          memory: 256Mi                
